name: "Terraform Plan on PR"
on:
  push:
    branches-ignore:
      - main

env:
  TF_VERSION: 1.0.3
  TF_INPUT: 0
  TF_IN_AUTOMATION: 1

defaults:
  run:
    shell: bash

jobs:
  plan_terraform:
    name: "Terraform Plan Actions"
    runs-on: ubuntu-latest

    steps:

      - name: "Update"
        run: sudo apt-get update
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Configure AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-2
      - name: "Docker Build"
        id: docker_build
        run: docker build -t 32682504/simple_time_service:latest .
      - name: "setup-terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
        continue-on-error: true
      - name: "Terraform Init"
        id: init
        run: terraform -chdir=terraform/ init -input=false
        env:
          TF_INPUT: 0
      - name: "Terraform Validate"
        id: validate
        run: terraform -chdir=terraform/ validate -no-color
        env:
          TF_INPUT: 0
      - name: "Terraform Plan"
        id: plan
        run: terraform -chdir=terraform/ plan -no-color -input=false
        env:
          TF_INPUT: 0
        
